/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExampleOfGUI;

/**
 *
 * @author WIN
 */
public class ThirdGUI extends java.awt.Frame {

    /**
     * Creates new form ThirdGUI
     */
    public ThirdGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        l1.setBackground(new java.awt.Color(255, 0, 51));
        l1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("UserName");
        add(l1);
        l1.setBounds(70, 40, 70, 19);

        textField1.setBackground(new java.awt.Color(102, 255, 204));
        add(textField1);
        textField1.setBounds(150, 40, 110, 20);

        label1.setBackground(new java.awt.Color(255, 0, 0));
        label1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Password");
        add(label1);
        label1.setBounds(70, 80, 70, 21);

        textField2.setBackground(new java.awt.Color(153, 255, 204));
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        add(textField2);
        textField2.setBounds(150, 80, 110, 20);

        button1.setBackground(new java.awt.Color(51, 255, 0));
        button1.setLabel("Save");
        add(button1);
        button1.setBounds(90, 140, 43, 24);

        button2.setBackground(new java.awt.Color(255, 0, 51));
        button2.setLabel("Cancle");
        add(button2);
        button2.setBounds(170, 140, 57, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Label l1;
    private java.awt.Label label1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
